[package]
name = "compiler"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
string-interner = "0.12"

[dev-dependencies]
once_cell = "1.8"
regex = "1.5"
test-generator = "0.3" 